### ISSUE TITLE
Private type on public interface makes it hard to mock out the response

### ISSUE THREAD

**Issue by aliotta** [Metronome-Industries/metronome-go#34]
The following List endpoint returns a type that is not made public making it difficult to make an interface for this method.

https://github.com/Metronome-Industries/metronome-go/blob/70b3a862ea59fd36d768932f55b33c7befeebbcc/customerinvoice.go#L59

**Comment by dgellow** [comment]
Hi @aliotta,

Could you clarify what type is causing issues for you? Both `pagination.CursorPage` and `Invoice` seem to be public as far as I can tell.

**Comment by dgellow** [comment]
Ah, you're perfectly right, `pagination` is under `internal`. That's definitely problematic. Thank you for the report, we are looking into it.
